FORMAT: 1A
HOST: http://www.google.com

# MLS
MLS API is a multiple listings service for homes

# Group Homes
Homes related resources of the **Homes API**

## Homes Collection [/homes]
### List all Homes [GET]
+ Response 200 (application/json)

        [{
          "id": 2, "address": "3756 Preston Street"
        }, {
          "id": 3, "address": "196 Woodside Circle"
        }]

## Home [/homes/{id}]
A single Home object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Home to perform action with. Has example value.

### Retrieve a Home [GET]
+ Request (application/json)

+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 3, "address": "196 Woodside Circle" }

## Favorites Collection [/favorites]
### List all Favorites [GET]
+ Response 200 (application/json)

        [{
          "id": 2, "address": "3756 Preston Street"
        }, {
          "id": 3, "address": "196 Woodside Circle"
        }]
        
### Create a Favorite [POST]
+ Request (application/json)

        { "id": 3 }

+ Response 201 (application/json)

### Remove a Favorite [DELETE]
+ Request (application/json)

        { "id": 3 }

+ Response 204

## Favorite [/favorites/{id}]
A single home object with all its detail
### Retrieve a Favorite [GET]
+ Request (application/json)

+ Response 200 (application/json)

        { "id": 3, "address": "196 Woodside Circle" }